### ISSUE TITLE
missing module when starting flask

### ISSUE THREAD

**Issue by mylbco** [mimusica/OCA_image_prepper#2]
* Debug mode: off
Usage: flask run [OPTIONS]
Try 'flask run --help' for help.

Error: While importing 'app', an ImportError was raised:

Traceback (most recent call last):
  File "/Users/peterl/docker/stoffel/OCA_image_prepper/.venv/lib/python3.9/site-packages/flask/cli.py", line 256, in locate_app
    __import__(module_name)
  File "/Users/peterl/docker/stoffel/OCA_image_prepper/app.py", line 13, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by mimusica** [comment]
Merged #3
